
###
POST http://localhost:3001/api/notes/ 
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im51ZXZvIiwiaWQiOiI2NmJhMWE0ZWM0NjZhODUwMTExNjIzZGUiLCJpYXQiOjE3MjM0NzcyMDV9.cTjOJJzZpptn0TrnXvxDdLcMINDnqnRvOng91YxCKPI

{
    "content": "esta nota la ha creado nuevo, hola soy yo",
    "important": true 
}

###
GET http://localhost:3001/api/notes/